//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniMerit.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class poc_file2
    {
        public int id { get; set; }
        public string poc_file { get; set; }
    }
}
