//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Institution_Code { get; set; }
        public string Book_Isbn_No { get; set; }
        public string Title { get; set; }
        public string Edition { get; set; }
        public string Publisher { get; set; }
        public string Shelf_No { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Book_No { get; set; }
        public string Author { get; set; }
        public Nullable<int> No_Of_Copies { get; set; }
        public string Position { get; set; }
        public string Language { get; set; }
        public string Book_Condition { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
        public int Book_Category { get; set; }
    
        public virtual Book_Category Book_Category1 { get; set; }
    }
}
