//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public int Id { get; set; }
        public string Institution_Code { get; set; }
        public string Pickup_Point { get; set; }
        public string Drop_Point { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Fee_Type { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
        public int Route_Code { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
