//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int Id { get; set; }
        public string Institution_Code { get; set; }
        public string Driver_Name { get; set; }
        public string Permanent_Address { get; set; }
        public string Present_Address { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Contact_No { get; set; }
        public string Licence_No { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
        public int Vehicle_No { get; set; }
    
        public virtual Transport_Detail Transport_Detail { get; set; }
    }
}
