//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee_Bank_Detail = new HashSet<Employee_Bank_Detail>();
            this.Salaries = new HashSet<Salary>();
            this.Students = new HashSet<Student>();
            this.Subject_Allocation = new HashSet<Subject_Allocation>();
        }
    
        public int Id { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Code { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public string Qualification { get; set; }
        public string Total_Experience { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_name { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Present_Address { get; set; }
        public string Permanent_Address { get; set; }
        public string City { get; set; }
        public Nullable<int> Pin { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string Email { get; set; }
        public int Department { get; set; }
        public int Designation { get; set; }
        public int User_Type { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Designation Designation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Bank_Detail> Employee_Bank_Detail { get; set; }
        public virtual User_Type User_Type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject_Allocation> Subject_Allocation { get; set; }
    }
}
