//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hostel_Registration
    {
        public int Id { get; set; }
        public string Institution_Code { get; set; }
        public string User_Type { get; set; }
        public string Hostel_Type { get; set; }
        public string Hostel_Name { get; set; }
        public string Hostel_Room { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public Nullable<System.DateTime> Vacating_Date { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
    }
}
