//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Id { get; set; }
        public string Institution_Code { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
        public int Designation { get; set; }
        public int Employee_Name { get; set; }
    
        public virtual Designation Designation1 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
