//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Parent_Detail
    {
        public int Id { get; set; }
        public string Institution_Code { get; set; }
        public string Father_Name { get; set; }
        public string Father_Mobile_No { get; set; }
        public string Father_Occupation { get; set; }
        public string Mother_Name { get; set; }
        public string Mother_Mobile_No { get; set; }
        public string Mother_Occupation { get; set; }
        public string Guradian_Name { get; set; }
        public string Guardian_Relation { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public string Income { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Phone_No { get; set; }
        public string Mobile_No { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
        public int Student_Id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
