//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Assign_Subject = new HashSet<Assign_Subject>();
            this.Elective_Subject_Allocation = new HashSet<Elective_Subject_Allocation>();
            this.Student_Personal_Detail = new HashSet<Student_Personal_Detail>();
            this.Student_Parent_Detail = new HashSet<Student_Parent_Detail>();
            this.Student_Prequalification_Detail = new HashSet<Student_Prequalification_Detail>();
        }
    
        public int Id { get; set; }
        public string Institution_Code { get; set; }
        public string Registration_No { get; set; }
        public string Roll_No { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public Nullable<int> Academic_Year { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
        public int Employee_Name { get; set; }
        public int Course { get; set; }
        public int Batch { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assign_Subject> Assign_Subject { get; set; }
        public virtual Batch Batch1 { get; set; }
        public virtual Course Course1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elective_Subject_Allocation> Elective_Subject_Allocation { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Personal_Detail> Student_Personal_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Parent_Detail> Student_Parent_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Prequalification_Detail> Student_Prequalification_Detail { get; set; }
    }
}
