//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Prequalification_Detail
    {
        public int Id { get; set; }
        public string Institution_Code { get; set; }
        public string School_Name { get; set; }
        public string School_Address { get; set; }
        public string Qualification { get; set; }
        public string Marklist { get; set; }
        public byte[] BirthCertificate { get; set; }
        public byte[] Transfer_C_C { get; set; }
        public byte[] Transfer_Certificate { get; set; }
        public byte[] Migration_Certificate { get; set; }
        public string Transport { get; set; }
        public string Hostel { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
        public int Student_Id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
