//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Personal_Detail
    {
        public int Id { get; set; }
        public string Institution_Code { get; set; }
        public string Frist_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Blood_Group { get; set; }
        public string Birth_Place { get; set; }
        public string Nationality { get; set; }
        public string Mother_Toungue { get; set; }
        public string Category { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string Permanent_Address { get; set; }
        public string Present_address { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Phone_No { get; set; }
        public string Mobile_No { get; set; }
        public string Email { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
        public int Student_Id { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
