//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnimerit.Data.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport_Allocation
    {
        public int Id { get; set; }
        public string Institution_Code { get; set; }
        public string Destination { get; set; }
        public string Transport_Type { get; set; }
        public string Start_From { get; set; }
        public string End_From { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
        public int Route_Code { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
